### ISSUE TITLE
Response Content-Type header incorrectly contains the quality qualifier.

### ISSUE THREAD

**Issue by MarkKharitonov** [openrasta/openrasta-hosting-aspnet#6]
Twin brother of https://github.com/openrasta/openrasta-core/issues/13, only relevant for the AspNet host.

**Comment by serialseb** [comment]
Hi!

Thanks for contributing, it's awesome! 😎

After reviewing, this does has already been fixed in other commits.

We are trying to keep our backlog fresh, and as this has not been updated for a while, I'm closing this issue. If you feel this was closed by mistake, or that it is still relevant, don't hesitate to comment and reopen it, and we'll re-evaluate.

Live long, and proper! 🖖🏽
